spring:
  application:
    name: node-center
  profiles:
    active: local
  datasource:
    #配置当前要使用的数据源的操作类型
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:grtidsp}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: xe
    password: reFHRExe08*$1               #jsumt1026@!@#szxm
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1 #配置redis的IP地址
    port: 6379 #该属性默认使用的是6379,如果你redis端口映射的不是6379可以通过这个属性来改
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.grtidsp.node.model
  configuration:
    #开启下划线到驼峰命名法的自动转换,将数据库字段根据驼峰规则自动注入到对象属性
    map-underscore-to-camel-case: true
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 8890
#文件暂存位置
file:
  upload:
    rootPath: E://data/grtidsp_node/
#     rootPath: /data/emipssp/

#引入日志配置文件
#=====================================  log  =============================
logging:
  config: classpath:logback-boot.xml
